### ISSUE TITLE
Can no longer plot data while it is being collected

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/databroker#141] opened 2017-03-07 16:40 UTC
We used to be able to do this but now get an error about a stop document missing.  This makes sense as the scan isn't complete, but this defeats the reason for SWMR for csx-tools, @stuwilkins knows more.

What is the reason for the change?

**Comment by tacaswell** [comment] 2017-03-09 19:02
Can you provide some code to reproduce this?

**Comment by ambarb** [comment] 2017-03-11 13:54
THis worked a few weeks ago.

````
def quickplt(scannums):

    st=[]
    et=[]
    sid=[]
    plt.figure()#figsize=(2,2))

    for scannum in scannums:
        tbl=get_table(db[scannum])
        h=db[scannum]
        st.append(h.start.time)
        et.append(h.stop.time)
        sid.append(h.start.scan_id)
        
        ####  tbl.[x-varible]  tbl.[y-variable]
        #plt.plot(tbl.pgm_energy_setpoint,tbl.fccd_stats1_total,label=scannum)  #add grating temperature here
        #plt.plot(tbl.energy,tbl.sclr_ch2,'-',label=scannum)  #add grating temperature here
        plt.plot(tbl.pgm_energy_setpoint,tbl.sclr_ch2,'--o',label=scannum)  #add grating temperature here
        plt.grid(True)
        
        #### plot x and y label and location of the legend.  1 = quadrant 1 of a standard x-y plot
        #plt.ylabel('FCCD STATS [a.u.]')
        #plt.xlabel('Energy Set Point [eV]')
        plt.legend(loc=1)
    
    
    begt=time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(st[0]))
    endt=time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(st[-1]))
    plt.title('%s   TO   %s\n' %(begt,endt))
    plt.show()
    print('\n[0] = scan id ;  [1] = scan start time ;  [2] = scan end time\n\n')
    return sid,st,et


scannums = [76124,76129]
    
data = quickplt(scannums)
````

OUTPUT IS NOW:
````
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-76-7f49c1a57435> in <module>()
     16 #    scannums.append(i)
     17 
---> 18 data = quickplt(scannums)
     19 
     20 #print('79 - roll 5.55, offset 17, phase 0 (H) ,80 - roll 5.55, offset 17, phase 0 (H),81 - roll 5.55, offset 17, phase 24.6 (,81 - roll 5.55, offset 17, phase 0 (H))')

<ipython-input-75-93986de13444> in quickplt(scannums)
     10         h=db[scannum]
     11         st.append(h.start.time)
---> 12         et.append(h.stop.time)
     13         sid.append(h.start.scan_id)
     14 

AttributeError: 'Header' object has no attribute 'stop'


````

**Comment by tacaswell** [comment] 2017-03-11 15:12
I don't think we have changed any of the installed software on the beamline since the shutdown.  Have you been committing this code to git regularly (that is very useful for tracking what changed)?

If you want this to run on non-finished scans, do something like


```python
try:
    et.append(h.stop.time)
except AttributeError:
    et.append(None)
```

**Comment by tacaswell** [comment] 2017-03-11 15:12
Which machine is this on?  The beamline or jupyter hub?

**Comment by ambarb** [comment] 2017-03-11 15:15
Jupyterhub srv1


Thomas A Caswell <notifications@github.com> wrote:


Which machine is this on? The beamline or jupyter hub?

**Comment by tacaswell** [comment] 2017-03-11 17:49
ah, not sure when version on that changed attn @danielballan

**Comment by tacaswell** [comment] 2017-04-25 15:07
Closing as local installation issues.

**Closed by tacaswell** 2017-04-25 15:07 UTC
