### ISSUE TITLE
Headers don't pretty print

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/databroker#148] opened 2017-03-17 16:43 UTC
It seems that ipython auto pretty print broke in the move to `Header` objects.
Also when `print(hdr)` is called I get back 3 printed copies.
```python
In [108]: print(hdr)

header
======
  
  EventDescriptor
  ---------------
  configuration   :
        pe1_number_of_se: 1                                       
        pe1_images_per_s: 600.0                                   
          source          : SIM:pe1_number_of_sets                  
          shape           : []                                      
          dtype           : number                                  
          source          : SIM:pe1_images_per_set                  
          shape           : []                                      
          dtype           : number                                  
        pe1_number_of_se: 1475709371.6344597                      
        pe1_images_per_s: 1475737775.2205236                      
  +------------------+--------+------------+------------------+-------------+-----------+-----------------+-------------------------------------------+-------+------------------+
  | data keys        | dtype  |  external  | lower_ctrl_limit | object_name | precision |      shape      |                   source                  | units | upper_ctrl_limit |
  +------------------+--------+------------+------------------+-------------+-----------+-----------------+-------------------------------------------+-------+------------------+
  | pe1_image        | array  | FILESTORE: |                  |     pe1     |           | [2048, 2048, 0] |         PV:XF:28IDC-ES:1{Det:PE1}         |       |                  |
  | pe1_stats1_total | number |            |       0.0        |     pe1     |     0     |        []       | PV:XF:28IDC-ES:1{Det:PE1}Stats1:Total_RBV |       |       0.0        |
  +------------------+--------+------------+------------------+-------------+-----------+-----------------+-------------------------------------------+-------+------------------+
  name            : primary                                 
  object_keys     :
    pe1             : ['pe1_image', 'pe1_stats1_total']       
  time            : 1475737908.980231                       
  uid             : cde61981-7ae0-4761-9f4b-f1e10a39b1b4    
      
      RunStart
      ````````
      beamline_id     : xpd                                     
      bkgd_geometry   : kapton_bkgd_1mmOD                       
      bt_experimenters: ['Maxwell', 'Terban', 'Bertolotti', 'Federica', 'Chia-Hao', 'Liu']
      bt_piLast       : Billinge                                
      bt_safN         : 300874                                  
      bt_uid          : bbbf141c                                
      bt_wavelength   : 0.183463                                
      calibration_coll: 14301160-06eb-4807-b346-58ddaf8c80f1    
      calibration_md  :
        time            : 20161005-1911                           
        rot2            : -0.0005143679573110852                  
        tilt            : 0.5107862954405932                      
        directDist      : 211.11527183961394                      
        pixelY          : 200.0                                   
        rot1            : 0.008900051768602826                    
        splineFile      : None                                    
        tiltPlanRotation: -176.69229377493303                     
        pixel1          : 0.0002                                  
        poni1           : 0.20874577192878496                     
        centerX         : 996.7282173197707                       
        rot3            : 1.3330806893924516e-08                  
        dist            : 0.21110688265045421                     
        wavelength      : 1.83463e-11                             
        pixelX          : 200.0                                   
        pixel2          : 0.0002                                  
        poni2           : 0.20122455525862507                     
        detector        : Perkin detector                         
        centerY         : 1043.1859050122002                      
        file_name       : pyFAI_calib_Ni_20161005-1911            
      cif_name        : ['nan']                                 
      collaborators   : ['nan']                                 
      database_id     :
        nan             : N/A                                     
      detectors       : ['pe1']                                 
      group           : XPD                                     
      lead_experimente: ['Federica', 'Bertolotti']              
      my_field_name   : nan                                     
      notes           : Solvent                                 
      num_steps       : 36                                      
      owner           : xf28id1                                 
      plan_args       :
        num             : 36                                      
        detectors       : ["PerkinElmerContinuous(prefix='XF:28IDC-ES:1{Det:PE1}', name='pe1', read_attrs=['tiff', 'stats1'], configuration_attrs=['images_per_set', 'number_of_sets'])"]
      plan_name       : count                                   
      plan_type       : generator                               
      sa_uid          : 7f5a142f                                
      sample_composition:
        H               : 8.0                                     
        C               : 7.0                                     
      sample_maker    : ['nan']                                 
      sample_name     : toluene                                 
      sample_phase    :
        C7H8            : 1.0                                     
      sc_dk_field_uid : 09c6ef6c-c91c-45a5-9093-48a1432e674f    
      scan_id         : 93                                      
      sp_computed_expo: 60.0                                    
      sp_num_frames   : 600.0                                   
      sp_plan_name    : tseries                                 
      sp_requested_exp: 60                                      
      sp_time_per_fram: 0.1                                     
      sp_type         : tseries                                 
      sp_uid          : 673f5786-8a34-4876-906b-961e306de9fa    
      tags            : ['blank']                               
      time            : 1475737844.1481683                      
      uid             : dff9ca9d-906d-40d6-911f-6fc2d8d47677    
  
  RunStart
  --------
  beamline_id     : xpd                                     
  bkgd_geometry   : kapton_bkgd_1mmOD                       
  bt_experimenters: ['Maxwell', 'Terban', 'Bertolotti', 'Federica', 'Chia-Hao', 'Liu']
  bt_piLast       : Billinge                                
  bt_safN         : 300874                                  
  bt_uid          : bbbf141c                                
  bt_wavelength   : 0.183463                                
  calibration_coll: 14301160-06eb-4807-b346-58ddaf8c80f1    
  calibration_md  :
    time            : 20161005-1911                           
    rot2            : -0.0005143679573110852                  
    tilt            : 0.5107862954405932                      
    directDist      : 211.11527183961394                      
    pixelY          : 200.0                                   
    rot1            : 0.008900051768602826                    
    splineFile      : None                                    
    tiltPlanRotation: -176.69229377493303                     
    pixel1          : 0.0002                                  
    poni1           : 0.20874577192878496                     
    centerX         : 996.7282173197707                       
    rot3            : 1.3330806893924516e-08                  
    dist            : 0.21110688265045421                     
    wavelength      : 1.83463e-11                             
    pixelX          : 200.0                                   
    pixel2          : 0.0002                                  
    poni2           : 0.20122455525862507                     
    detector        : Perkin detector                         
    centerY         : 1043.1859050122002                      
    file_name       : pyFAI_calib_Ni_20161005-1911            
  cif_name        : ['nan']                                 
  collaborators   : ['nan']                                 
  database_id     :
    nan             : N/A                                     
  detectors       : ['pe1']                                 
  group           : XPD                                     
  lead_experimente: ['Federica', 'Bertolotti']              
  my_field_name   : nan                                     
  notes           : Solvent                                 
  num_steps       : 36                                      
  owner           : xf28id1                                 
  plan_args       :
    num             : 36                                      
    detectors       : ["PerkinElmerContinuous(prefix='XF:28IDC-ES:1{Det:PE1}', name='pe1', read_attrs=['tiff', 'stats1'], configuration_attrs=['images_per_set', 'number_of_sets'])"]
  plan_name       : count                                   
  plan_type       : generator                               
  sa_uid          : 7f5a142f                                
  sample_composition:
    H               : 8.0                                     
    C               : 7.0                                     
  sample_maker    : ['nan']                                 
  sample_name     : toluene                                 
  sample_phase    :
    C7H8            : 1.0                                     
  sc_dk_field_uid : 09c6ef6c-c91c-45a5-9093-48a1432e674f    
  scan_id         : 93                                      
  sp_computed_expo: 60.0                                    
  sp_num_frames   : 600.0                                   
  sp_plan_name    : tseries                                 
  sp_requested_exp: 60                                      
  sp_time_per_fram: 0.1                                     
  sp_type         : tseries                                 
  sp_uid          : 673f5786-8a34-4876-906b-961e306de9fa    
  tags            : ['blank']                               
  time            : 1475737844.1481683                      
  uid             : dff9ca9d-906d-40d6-911f-6fc2d8d47677    
  
  RunStop
  -------
  exit_status     : success                                 
  time            : 1475761955.610756                       
  uid             : 1291a1a1-3334-444b-b8e7-ef718713c93f    
      
      RunStart
      ````````
      beamline_id     : xpd                                     
      bkgd_geometry   : kapton_bkgd_1mmOD                       
      bt_experimenters: ['Maxwell', 'Terban', 'Bertolotti', 'Federica', 'Chia-Hao', 'Liu']
      bt_piLast       : Billinge                                
      bt_safN         : 300874                                  
      bt_uid          : bbbf141c                                
      bt_wavelength   : 0.183463                                
      calibration_coll: 14301160-06eb-4807-b346-58ddaf8c80f1    
      calibration_md  :
        time            : 20161005-1911                           
        rot2            : -0.0005143679573110852                  
        tilt            : 0.5107862954405932                      
        directDist      : 211.11527183961394                      
        pixelY          : 200.0                                   
        rot1            : 0.008900051768602826                    
        splineFile      : None                                    
        tiltPlanRotation: -176.69229377493303                     
        pixel1          : 0.0002                                  
        poni1           : 0.20874577192878496                     
        centerX         : 996.7282173197707                       
        rot3            : 1.3330806893924516e-08                  
        dist            : 0.21110688265045421                     
        wavelength      : 1.83463e-11                             
        pixelX          : 200.0                                   
        pixel2          : 0.0002                                  
        poni2           : 0.20122455525862507                     
        detector        : Perkin detector                         
        centerY         : 1043.1859050122002                      
        file_name       : pyFAI_calib_Ni_20161005-1911            
      cif_name        : ['nan']                                 
      collaborators   : ['nan']                                 
      database_id     :
        nan             : N/A                                     
      detectors       : ['pe1']                                 
      group           : XPD                                     
      lead_experimente: ['Federica', 'Bertolotti']              
      my_field_name   : nan                                     
      notes           : Solvent                                 
      num_steps       : 36                                      
      owner           : xf28id1                                 
      plan_args       :
        num             : 36                                      
        detectors       : ["PerkinElmerContinuous(prefix='XF:28IDC-ES:1{Det:PE1}', name='pe1', read_attrs=['tiff', 'stats1'], configuration_attrs=['images_per_set', 'number_of_sets'])"]
      plan_name       : count                                   
      plan_type       : generator                               
      sa_uid          : 7f5a142f                                
      sample_composition:
        H               : 8.0                                     
        C               : 7.0                                     
      sample_maker    : ['nan']                                 
      sample_name     : toluene                                 
      sample_phase    :
        C7H8            : 1.0                                     
      sc_dk_field_uid : 09c6ef6c-c91c-45a5-9093-48a1432e674f    
      scan_id         : 93                                      
      sp_computed_expo: 60.0                                    
      sp_num_frames   : 600.0                                   
      sp_plan_name    : tseries                                 
      sp_requested_exp: 60                                      
      sp_time_per_fram: 0.1                                     
      sp_type         : tseries                                 
      sp_uid          : 673f5786-8a34-4876-906b-961e306de9fa    
      tags            : ['blank']                               
      time            : 1475737844.1481683                      
      uid             : dff9ca9d-906d-40d6-911f-6fc2d8d47677
```

**Comment by tacaswell** [comment] 2017-03-18 03:36
duplicate of #133

**Closed by tacaswell** 2017-03-18 03:36 UTC
